---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    #set these here becuase they get pulled out by testem saucie
    - SAUCE_USERNAME="ilios"
    - SAUCE_ACCESS_KEY="e7c24f1d-ec10-435d-9cec-d1c38bafa268"
    - START_SAUCE_CONNECT=false
    - JS_TESTS=true
    - SCSS_LINT=false
    - TESTEM_LAUNCHER='PhantomJS'

matrix:
  fast_finish: true
  allow_failures:
    # IE10 builds allowed to fail until https://github.com/edgycircle/ember-pikaday/issues/21 is fixed
    - env: "TESTEM_LAUNCHER='SL_internet_explorer_10' START_SAUCE_CONNECT=true JS_TESTS=true"
  include:
    - env: "TESTEM_LAUNCHER='SL_chrome' START_SAUCE_CONNECT=true JS_TESTS=true"
    - env: "TESTEM_LAUNCHER='SL_firefox' START_SAUCE_CONNECT=true JS_TESTS=true"
    - env: "TESTEM_LAUNCHER='SL_internet_explorer_10' START_SAUCE_CONNECT=true JS_TESTS=true"
    - env: "TESTEM_LAUNCHER='SL_internet_explorer_11' START_SAUCE_CONNECT=true JS_TESTS=true"
    - env: "TESTEM_LAUNCHER='SL_safari_7' START_SAUCE_CONNECT=true JS_TESTS=true"
    - env: "JS_TESTS=false SCSS_LINT=true"

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - if [ "$JS_TESTS" = true ]; then npm install -g bower; fi
  - if [ "$JS_TESTS" = true ]; then travis_retry npm install; fi
  - if [ "$JS_TESTS" = true ]; then travis_retry bower install; fi
  - if [ "$SCSS_LINT" = true ]; then travis_retry gem install scss-lint; fi

before_script:
  # Create a sauce tunnel
  - if [ "$START_SAUCE_CONNECT" = true ]; then travis_retry ember start-sauce-connect; fi

script:
  - if [ "$SCSS_LINT" = true ]; then scss-lint; fi
  - if [ "$JS_TESTS" = true ]; then node_modules/.bin/ember test --port=8080 --launch=${TESTEM_LAUNCHER}; fi

after_script:
  # Destroy the sauce tunnel
  - if [ "$START_SAUCE_CONNECT" = true ]; then ember stop-sauce-connect; fi

#encrypted the slack token to post to #info so that it doesn't run on pull requests or forks
notifications:
    slack:
      secure: oloxDKdwXmNHKhh5WSR8DDxA3WJdAnyj+vj/8yawF1zG0tgL4fyPzzFqSpEhfsfgBrJlvxFtSnnsWEIMSMdT1LTwReClyjsy3PFQnHIiLMv/IZUS7ijahXQ4XL+ejfyPV4rJtFuKOLuNMww8uniy705/QkqBYwFUAcXXQ3gV5V8=
